var destinazioni = [
    {
        "nome": "residenziale",
        "usi": ["Abitazione",
                "Balcone",
                "Terrazzo",
                "Lastrico",
                "Portico",
                "Accessori diretti agibili (sottotetto)",
                "Accessori diretti agibili (taverna)",
                "Accessori indiretti (cantina)",
                "Accessori indiretti (solaio)",
                "Accessori indiretti (ripostiglio)",
                "Accessori diretti abitabili (mansarda)",
                "Verande - logge",
                "Box auto",
                "Posto auto coperto",
                "Posto auto scoperto",
                "Giardino (fino ai mq. dell'unità)",
                "Giardino (oltre i mq. dell'unità)"]
    },
    {
        "nome": "commerciale",
        "usi": ["Destinazione prevalente e/o assimilabile",
                "Cantina",
                "Cantina collegata da scala interna",
                "Sotto negozio ad uso di superficie di vendita",
                "Locali tecnici/magazzini",
                "Posti auto scoperti",
                "Posti auto coperti",
                "Box",
                "Piano primo direttamente collegato ad uso di superficie di vendita",
                "Balcone fino a mq 9",
                "Terrazzo con superficie < alla superficie dell'unità immobiliare",
                "Terrazzo con superficie > alla superficie dell'unità immobiliare",
                "Terrazzo non al piano",
                "Tettoie esterne",
                "Cortile pavimentato",
                "Cortile pavimentato e carrabile",
                "Giardino con superficie < alla superficie dell'unità immobiliare",
                "Giardino con superficie fino al doppio della superficie dell'unità immobiliare",
                "Giardino con superficie > al doppio della superficie dell'unità immobiliare",
                "Giardino con superficie nettamente maggiore alla superficie dell'unità immobiliare",
                "Connettivi nel caso di immobili cielo terra"]
    },
    {
        "nome": "direzionale",
        "usi": ["Destinazione prevalente e/o assimilabile",
                "Cantina",
                "Cantina collegata da scala interna",
                "Archivi",
                "Locali tecnici/magazzini",
                "Posti auto scoperti",
                "Posti auto coperti",
                "Box",
                "Soffitta",
                "Mansarda",
                "Mansarda collegata da scala interna",
                "Mensa",
                "Balcone fino a mq 9",
                "Terrazzo con superficie < alla superficie dell'unità immobiliare",
                "Terrazzo con superficie > alla superficie dell'unità immobiliare",
                "Terrazzo non al piano",
                "Tettoie esterne",
                "Cortile pavimentato",
                "Cortile pavimentato e carrabile",
                "Giardino con superficie < alla superficie dell'unità immobiliare",
                "Giardino con superficie fino al doppio della superficie dell'unità immobiliare",
                "Giardino con superficie > al doppio della superficie dell'unità immobiliare",
                "Giardino con superficie nettamente maggiore alla superficie dell'unità immobiliare",
                "Connettivi nel caso di immobili cielo terra"]
    },
    {
        "nome": "produttivo",
        "usi": ["Destinazione prevalente e/o assimilabile",
                "Cantina",
                "Cantina collegata da scala interna",
                "Archivi",
                "Locali tecnici/magazzini",
                "Posti auto scoperti",
                "Posti auto coperti",
                "Box",
                "Soffitta",
                "Soppalco",
                "Soppalco sfruttabile per attività produttiva",
                "Balcone fino a mq 9",
                "Terrazzo con superficie < alla superficie dell'unità immobiliare",
                "Terrazzo con superficie > alla superficie dell'unità immobiliare",
                "Terrazzo non al piano",
                "Tettoie esterne",
                "Cortile pavimentato",
                "Cortile pavimentato e carrabile",
                "Area esterna con superficie < alla superficie dell'unità immobiliare",
                "Area esterna con superficie fino al doppio della superficie dell'unità immobiliare",
                "Area esterna con superficie > al doppio della superficie dell'unità immobiliare",
                "Area esterna con superficie nettamente maggiore alla superficie dell'unità immobiliare",
                "Connettivi nel caso di immobili cielo terra"]
    }
];